name: gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.0 --ignore-installed
    - pandas
    - lxml
    - tqdm
    - -e .
