name: cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - git
  - pip:
    - tensorflow==2.0
    - pandas
    - lxml
    - tqdm
    - -e .
    - pyqt5-sip
    - pyqt5
    - h5py==2.10
