name: gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - git
  - pip:
    - tensorflow-gpu==2.1.0
    - pandas
    - lxml
    - tqdm
    - -e .
    - pyqt5-sip
    - pyqt5
    - h5py==2.10
